import Head from "next/head"
import Image from "next/image"
import axios from "axios"
import styles from "../../styles/Home.module.css"
// next渲染，ssr和ssg渲染和区别
function Blog({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>测试阿毛列表首页</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((item) => (
          <div key={item.id}>{item.setMealName}</div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// export async function getStaticProps() {
// SSG渲染-每次build的时候获取数据，start之后保持数据不变
//   const res = await axios.get(
//     "http://114.55.106.181:7300/mock/60e01906a67078595d9aac7f/pangu/hms/nuwa/appApi/admin/setMeal/makeup"
//   )
//   console.log(res.data.data.list)
//   return {
//     props: {
//       posts: res.data.data.list,
//     },
//   }
// }

export async function getServerSideProps() {
  // SSR渲染-每次页面刷新都会重新请求一次接口数据
  const res = await axios.get(
    "http://114.55.106.181:7300/mock/60e01906a67078595d9aac7f/pangu/hms/nuwa/appApi/admin/setMeal/makeup"
  )
  console.log(res.data.data.list)
  return {
    props: {
      posts: res.data.data.list,
    },
  }
}
export default Blog
