import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script
        type="text/javascript"
        src="//cdn-4.convertexperiments.com/js/1004382-1004226.js"
      ></script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
