import Head from "next/head"
import Image from "next/image"
import axios from "axios"
import styles from "../styles/Home.module.css"
import TestSsr from "../components/TestSsr"
// next.js ISR渲染-(Incremental Static Regeneration)-增量静态再生成
// 目前需求上没有动态path需求，因此考虑先仅设置getStaticProps，不设置getStaticPaths,revalidate开启静态数据时间
function Blog({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>测试阿毛列表首页</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TestSsr></TestSsr>
        {posts.map((item) => (
          <div key={item.id}>{item.setMealName}</div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// export async function getStaticProps() {
// SSG渲染-每次build的时候获取数据，start之后保持数据不变
// const res = await axios.get(
//   "http://114.55.106.181:7300/mock/60e01906a67078595d9aac7f/pangu/hms/nuwa/appApi/admin/setMeal/makeup"
// )
// console.log(res.data.data.list)
// return {
//   props: {
//     posts: res.data.data.list,
//   },
// }
// }

// export async function getStaticPaths() {
//   const paths = await axios.get(
//     "http://114.55.106.181:7300/mock/60e01906a67078595d9aac7f/pangu/hms/nuwa/appApi/admin/setMeal/makeup"
//   )
//   return {
//     paths,
//     // 頁面請求的降級策略，這裏是指不降級，等待頁面生成後再返回，類似於 SSR
//     fallback: true,
//   }
// }

export async function getStaticProps({ params }) {
  // 使用 params.id 獲取對應的靜態數據
  const res = await axios.get(
    "http://114.55.106.181:7300/mock/60e01906a67078595d9aac7f/pangu/hms/nuwa/appApi/admin/setMeal/makeup"
  )
  console.log(res.data.data.list)
  return {
    props: {
      posts: res.data.data.list,
    },
    // 開啟 ISR，最多每10s重新生成一次頁面
    revalidate: 60,
  }
}
export default Blog
